WebMoney/Controllers/BankController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Linq;
using System.Threading.Tasks;
using WebMoney.Entities;
using WebMoney.Enums;
using WebMoney.Models;
using WebMoney.Services;
using WebMoney.ViewModels;

namespace WebMoney.Controllers
{
    public class BankController : Controller
    {
        private readonly EmailService emailService;
        private ApplicationDbContext _context;
        public BankController(IServiceProvider serviceProvider)
        {
            _context = serviceProvider.GetRequiredService<ApplicationDbContext>();
            this.emailService = serviceProvider.GetRequiredService<EmailService>();
        }
        public IActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
                return RedirectToAction("Index", "Profile");
            else
                return View();
        }
        [HttpPost]
        public async Task<JsonResult> AnonymousTransfer(AnonymousTransferViewModel model)
        {
            var transfer = new Transaction()
            {
                MoneyCount = model.MoneyCount,
                WalletTo = model.WalletNumber,
                WalletFrom = "Anonymous",
                DateTime = DateTime.Now,
                TransactionType = TransactionType.Transfer
            };
            var wallet = await _context.BankAccounts.FirstOrDefaultAsync(b => b.UniqueNumber == model.WalletNumber);
            if (wallet == null)
                return Json("Такого кошелька не существует!");
            else
            {
                wallet.MoneyCount += transfer.MoneyCount;
                await _context.Transactions.AddAsync(transfer);
                await _context.SaveChangesAsync();
                var user = await _context.Users.FirstOrDefaultAsync(u => u.Id == wallet.UserId);
                emailService.SendEmailCustom(user.Email, "На ваш счёт был совершен перевод от анонимного пользователя. На ваш счёт поступило: " + transfer.MoneyCount + "$");
                return Json("200");
            }


        }
        [Authorize]
        [HttpPost]
        public async Task<JsonResult> DefaultTransfer(AnonymousTransferViewModel model)
        {
            var user = await _context.Users.FirstOrDefaultAsync(u => u.UserName == User.Identity.Name);
            var myWallet = await _context.BankAccounts.FirstOrDefaultAsync(b => b.UserId == user.Id);
            var transfer = new Transaction()
            {
                MoneyCount = model.MoneyCount,
                WalletTo = model.WalletNumber,
                WalletFrom = myWallet.UniqueNumber,
                DateTime = DateTime.Now,
                TransactionType = TransactionType.Transfer
            };
            var wallet = await _context.BankAccounts.FirstOrDefaultAsync(b => b.UniqueNumber == model.WalletNumber);
            if (myWallet.MoneyCount < model.MoneyCount)
                return Json("На вашем кошельке недостаточно денег!");
            if (wallet == null)
                return Json("Такого кошелька не существует!");
            else
            {
                wallet.MoneyCount += transfer.MoneyCount;
                myWallet.MoneyCount -= transfer.MoneyCount;
                await _context.Transactions.AddAsync(transfer);
                await _context.SaveChangesAsync();
                var anotherUser = await _context.Users.FirstOrDefaultAsync(u => u.Id == wallet.UserId);
                emailService.SendEmailCustom(user.Email, "Вы совершили перевод на счёт пользователя" + anotherUser.UserName + " Вы перевели: " + transfer.MoneyCount + "$");
                emailService.SendEmailCustom(user.Email, "На ваш счёт был совершен перевод от пользователя " + user.UserName + " На ваш счёт поступило: " + transfer.MoneyCount + "$");
                return Json("200");
            }
        }
        [Authorize]
        [HttpPost]
        public async Task<JsonResult> GetMoney(double moneyCount)
        {
            var user = await _context.Users.FirstOrDefaultAsync(u => u.UserName == User.Identity.Name);
            var myWallet = await _context.BankAccounts.FirstOrDefaultAsync(b => b.UserId == user.Id);
            var transfer = new Transaction()
            {
                MoneyCount = moneyCount,
                WalletTo = myWallet.UniqueNumber,
                WalletFrom = myWallet.UniqueNumber,
                DateTime = DateTime.Now,
                TransactionType = TransactionType.Withdrawal
            };
            if (myWallet.MoneyCount < moneyCount)
                return Json("На вашем кошельке недостаточно денег!");
            myWallet.MoneyCount -= moneyCount;
            await _context.Transactions.AddAsync(transfer);
            await _context.SaveChangesAsync();
            emailService.SendEmailCustom(user.Email, "Вы сняли с вашего счёта" + transfer.MoneyCount + "$" + "На вашем счету сейчас " + myWallet.MoneyCount + "$");
            return Json("200");
        }
        [Authorize]
        [HttpPost]
        public async Task<JsonResult> AddMoney(double moneyCount)
        {
            var user = await _context.Users.FirstOrDefaultAsync(u => u.UserName == User.Identity.Name);
            var myWallet = await _context.BankAccounts.FirstOrDefaultAsync(b => b.UserId == user.Id);
            var transfer = new Transaction()
            {
                MoneyCount = moneyCount,
                WalletTo = myWallet.UniqueNumber,
                WalletFrom = myWallet.UniqueNumber,
                DateTime = DateTime.Now,
                TransactionType = TransactionType.Refill
            };
            myWallet.MoneyCount += moneyCount;
            await _context.Transactions.AddAsync(transfer);
            await _context.SaveChangesAsync();
            emailService.SendEmailCustom(user.Email, "Вы пополнили свой счёт" + transfer.MoneyCount + "$" + "На вашем счету сейчас " + myWallet.MoneyCount + "$");
            return Json("200");
        }
        [Authorize]
        public async Task<IActionResult> History(string dateFrom, string dateTo)
        {
            var user = await _context.Users.FirstOrDefaultAsync(u => u.UserName == User.Identity.Name);
            var myWallet = await _context.BankAccounts.FirstOrDefaultAsync(b => b.UserId == user.Id);
            var history = await _context.Transactions.Where(h => h.WalletFrom == myWallet.UniqueNumber || h.WalletTo == myWallet.UniqueNumber).ToListAsync();
            if (!String.IsNullOrEmpty(dateFrom))
                history = history.Where(p => p.DateTime > Convert.ToDateTime(dateFrom)).ToList();
            if (!String.IsNullOrEmpty(dateTo))
                history = history.Where(p => p.DateTime < Convert.ToDateTime(dateTo)).ToList();

            var historyViewModel = new HistoryViewModel()
            {
                Transactions = history
            };
            return View(historyViewModel);
        }
        [Authorize]
        [HttpPost]
        public async Task<JsonResult> Pay(int id, double moneyCount)
        {
            var user = await _context.Users.FirstOrDefaultAsync(u => u.UserName == User.Identity.Name);
            var myWallet = await _context.BankAccounts.FirstOrDefaultAsync(b => b.UserId == user.Id);
            var companyUser = await _context.CompanyUsers.FirstOrDefaultAsync(c => c.CompanyId == id);
            var transfer = new Transaction()
            {
                MoneyCount = moneyCount,
                WalletTo = companyUser.Walletnumber,
                WalletFrom = myWallet.UniqueNumber,
                DateTime = DateTime.Now,
                TransactionType = TransactionType.PaymentForServices
            };
            var wallet = await _context.BankAccounts.FirstOrDefaultAsync(b => b.UniqueNumber == companyUser.Walletnumber);
            if (myWallet.MoneyCount < moneyCount)
                return Json("На вашем кошельке недостаточно денег!");
            else
            {
                wallet.MoneyCount += transfer.MoneyCount;
                myWallet.MoneyCount -= transfer.MoneyCount;
                await _context.Transactions.AddAsync(transfer);
                await _context.SaveChangesAsync();
                var anotherUser = _context.Users.FirstOrDefault(u => u.Id == wallet.UserId);
                emailService.SendEmailCustom(user.Email, "Вы совершили оплату услуг компании: " + (await _context.ServiceCompanies.FirstOrDefaultAsync(c => c.Id == id)).Name + " Вы потратили: " + transfer.MoneyCount + "$");
                return Json("200");
            }
        }
    }
}

WebMoney/Controllers/ServiceController.cs
using Microsoft.AspNetCore.Mvc;
using WebMoney.Models;
using WebMoney.Services;

namespace WebMoney.Controllers
{
    public class ServiceController : Controller
    {
        private ApplicationDbContext _context;
        public ServiceController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var companies = _context.ServiceCompanies;
            return View(companies);
        }
    }
}

WebMoney/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebMoney</title>
    <script src="https://kit.fontawesome.com/1f84b24a08.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                @if (User.Identity.IsAuthenticated)
                {
                    <a class="navbar-brand" asp-area="" asp-controller="Profile" asp-action="Index"><span style="font-size: 36px;"> <i class="far fa-money-bill-alt"></i> </span> </a>
                }
                else
                {
                    <a class="navbar-brand" asp-area="" asp-controller="Bank" asp-action="Index"><span style="font-size: 36px;"> <i class="far fa-money-bill-alt"></i> </span> </a>
                }
                <div class="login_group d-flex row ml-auto">
                    @if (User.Identity.IsAuthenticated)
                    {

                        <p class="mt-2">
                            <a class="mx-2 btn mb-0 btn-primary" asp-action="Index" asp-controller="Profile" asp-route-name="@User.Identity.Name">Кабинет</a>
                        </p>
                        <p class="mt-2">
                            <a class="mx-2 btn mb-0 btn-primary" asp-action="Index" asp-controller="Service">Оплата услуг</a>
                        </p>
                        <form class="mt-2" method="post" asp-controller="Account" asp-action="LogOff">
                            <input type="submit" class="ml-2 mb-0 btn btn-primary" value="Выход" />
                        </form>

                    }
                    else
                    {

                        <a class="mx-2 btn btn-primary" asp-controller="Account" asp-action="Login">Вход</a>
                        <a class="mx-2 btn btn-primary" asp-controller="Account" asp-action="Register">Регистрация</a>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WebMoney - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>